//! Write standards-conformant NTSC/PAL reference captures as SigMF
//! (`.sigmf-data` + `.sigmf-meta`), for testing decoders end to end.
//!
//! These are generated by [`synthetic::generate_iq`], the same generator
//! the crate's calibrated tests use — full VBI structure (pre-equalising,
//! serrated broad, post-equalising pulses), correct half-line interlace
//! offset per parity, and standards line/field rates. A decoder that
//! handles these should report the right standard, the right geometry,
//! and a sync quality near 1.0 on *every* field, both parities.
//!
//! That last property is what makes them useful: a capture whose alternate
//! fields decode poorly is telling you about the capture, not the decoder.
//!
//! Examples:
//!   cargo run --release --example make_reference_capture -- --standard pal
//!   cargo run --release --example make_reference_capture -- \
//!       --standard ntsc --noise-sigma 0.5 --out /tmp/ntsc_weak
//!
//! `--noise-sigma` adds complex AWGN (per I/Q component, against a
//! unit-amplitude carrier) to build weak-signal variants.
//!
//! # No pre-emphasis
//!
//! These carry the *canonical* video waveform — no VTX pre-emphasis
//! curve baked in. That is deliberate: a reference should be the signal
//! the standard describes, not one tied to a particular transmitter's
//! emphasis. (It is also the only self-consistent choice here. The exact
//! inverse of a 0.75 µs single-pole deemphasis applied to the
//! generator's hard sync edges asks for ~12× the FM deviation on every
//! transition — unphysical, and it would alias.)
//!
//! So `--deemphasis-tau 0` reproduces the generated waveform exactly.
//! The viewer's *default* 0.75 µs deemphasis also decodes these
//! correctly — it just softens the picture, having no pre-emphasis to
//! undo. Checking both is worthwhile: sync detection surviving that gain
//! change is what `sync_survives_deemphasis_gain_change` guards, after a
//! fixed-threshold version of it failed every line of every field.

use num_complex::Complex;
use orecchiette_fpv_drone_analog_rs::synthetic::{SyntheticVideoConfig, TestPattern, generate_iq};
use orecchiette_fpv_drone_analog_rs::vbi::FieldParity;
use std::io::Write;

fn arg(name: &str, default: &str) -> String {
    let args: Vec<String> = std::env::args().collect();
    args.iter()
        .position(|a| a == name)
        .and_then(|i| args.get(i + 1).cloned())
        .unwrap_or_else(|| default.to_string())
}

/// Deterministic Irwin-Hall approximation of N(0,1) — no rand dependency,
/// so captures are byte-reproducible from the same arguments.
fn gauss(state: &mut u64) -> f32 {
    let mut acc = 0.0f32;
    for _ in 0..12 {
        *state ^= *state << 13;
        *state ^= *state >> 7;
        *state ^= *state << 17;
        acc += (*state >> 11) as f32 / (1u64 << 53) as f32;
    }
    acc - 6.0
}

fn main() -> std::io::Result<()> {
    let standard = arg("--standard", "pal").to_lowercase();
    let is_pal = match standard.as_str() {
        "pal" => true,
        "ntsc" => false,
        other => {
            eprintln!("unknown --standard '{other}' (expected pal or ntsc)");
            std::process::exit(2);
        }
    };
    let sample_rate: u32 = arg("--sample-rate", "15360000")
        .parse()
        .expect("--sample-rate");
    let deviation: f32 = arg("--deviation", "5000000").parse().expect("--deviation");
    let fields: usize = arg("--fields", "8").parse().expect("--fields");
    let noise_sigma: f32 = arg("--noise-sigma", "0").parse().expect("--noise-sigma");
    let center_hz: f64 = arg("--center", "5800000000").parse().expect("--center");
    let out = arg("--out", &format!("reference_{standard}"));

    let cfg = SyntheticVideoConfig {
        sample_rate,
        is_pal,
        deviation_hz: deviation,
        pattern: TestPattern::Bars,
        start_field: FieldParity::First,
        noise_sigma: 0.0,
        dc_offset: 0.0,
    };

    // Signal is generated at baseband (carrier at DC) — decoders tune to
    // the capture centre with no offset, which is the simplest correct
    // thing for a reference file.
    let mut iq: Vec<Complex<f32>> = generate_iq(&cfg, fields, 0.0);

    if noise_sigma > 0.0 {
        let mut seed = 0x5EED_1234_ABCD_0001u64;
        for z in iq.iter_mut() {
            z.re += noise_sigma * gauss(&mut seed);
            z.im += noise_sigma * gauss(&mut seed);
        }
    }

    let data_path = format!("{out}.sigmf-data");
    let meta_path = format!("{out}.sigmf-meta");

    let mut f = std::io::BufWriter::new(std::fs::File::create(&data_path)?);
    for z in &iq {
        f.write_all(&z.re.to_le_bytes())?;
        f.write_all(&z.im.to_le_bytes())?;
    }
    f.flush()?;

    let label = if is_pal { "PAL" } else { "NTSC" };
    let half_bw = (deviation * 2.0) as f64;
    let meta = format!(
        r#"{{
  "global": {{
    "core:datatype": "cf32_le",
    "core:sample_rate": {sample_rate},
    "core:version": "1.0.0",
    "core:description": "Standards-conformant synthetic analog FPV {label} video, FM modulated at baseband. Generated by orecchiette-fpv-drone-analog-rs examples/make_reference_capture (synthetic::generate_iq): full VBI structure and correct half-line interlace offset on both field parities. {fields} fields, AWGN sigma {noise_sigma} per I/Q component. No VTX pre-emphasis is applied, so --deemphasis-tau 0 reproduces the generated waveform exactly; the default 0.75 us deemphasis also decodes correctly, just softer.",
    "core:recorder": "orecchiette-fpv-drone-analog-rs make_reference_capture",
    "fpv:fm_deviation": {deviation}
  }},
  "captures": [
    {{
      "core:sample_start": 0,
      "core:frequency": {center_hz}
    }}
  ],
  "annotations": [
    {{
      "core:sample_start": 0,
      "core:freq_lower_edge": {lo},
      "core:freq_upper_edge": {hi},
      "core:label": "{label}"
    }}
  ]
}}
"#,
        sample_rate = sample_rate,
        label = label,
        fields = fields,
        noise_sigma = noise_sigma,
        deviation = deviation,
        center_hz = center_hz,
        lo = -half_bw / 2.0,
        hi = half_bw / 2.0,
    );
    std::fs::write(&meta_path, meta)?;

    let secs = iq.len() as f64 / sample_rate as f64;
    println!(
        "wrote {data_path} ({} samples, {:.2} s) + {meta_path}\n  {label}, {:.3} MSPS, {:.1} MHz deviation, {fields} fields, noise sigma {noise_sigma}",
        iq.len(),
        secs,
        sample_rate as f64 / 1e6,
        deviation / 1e6,
    );
    Ok(())
}
